name: Deploy
run-name: Deploy to Vercel
on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: 'deploy'
  cancel-in-progress: false

jobs:
  deploy-vercel:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        env:
          PROJECT_JSON: ${{ secrets.VERCEL_PROJECT_JSON }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          DOT_ENV: ${{ secrets.DOT_NEV }}
        run: |
          mkdir .vercel
          echo -n "$PROJECT_JSON" > .vercel/project.json
          echo -n "$DOT_ENV" > .env
          npx vercel --prod --token $VERCEL_TOKEN
